### ISSUE TITLE
Add another location for blueprints directory

### ISSUE THREAD

**Issue by ajw107** [koter84/HomeAssistant_Blueprints_Update#11]
Hi

I have installed Home Assistant on top of Ubuntu, and so because of this my config directory is  `/usr/share/hassio/homeassistant/blueprints/`.  This fails the test in your code when checking for the existance of the blueprints directory.  As it's a pretty standard location, would it be possible for you to add this directory to your script?
Thanks for your help.

**Comment by koter84** [comment]
i've added this in the last commit
