### ISSUE TITLE
Message malformed: required key not provided @ data['trigger']

### ISSUE THREAD

**Issue by itsmartinho** [koter84/HomeAssistant_Blueprints_Update#4]
Getting this error when importing the Blueprints, did anyone else came across this, or is it outdate?
It seems to also go "nuts" with the data_template part, at least on the UI.

**Comment by koter84** [comment]
can you post the link to the blueprint ?

**Comment by koter84** [comment]
oops, i forgot to actually test the yaml in my HA install..

it's fixed now
